Wrap C++ literal strings in std::string constructors
In the morloc expression:

```
ifelse cond x ""
```

Where ifelse has the C++ implementation:

```
template <class A>
A morloc_ifelse(bool cond, A x, A y){
    if (cond) {
        return x;
    } else {
        return y;
    }
}
```

And `x` has type `std::string` and `cond` has type `bool`. gcc raises an
error:

```
deduced conflicting types for parameter ‘A’ (‘std::__cxx11::basic_string<char>’ and ‘const char*’)
```

It didn't automatically cast the string literal to a `std::string`. One
solution to this is to automatically turn all string primitives to
`std::string`, which is what I've done.