(5/370 fail) Found more bugs
A new bug involves is covered in the new golden test interop-4:

```
import pybase (add)
import rbase (map)

foo R :: ["numeric"] -> ["numeric"]
foo = map (add 1.0)

export foo
```

This raises a the error

```
SerializationError: Cannot unpack a passthrough typed expression
```

at `CodeGenerator.Grammar.Common:196

The problem is that `add 1.0` returns a serialized python float. `map`
is an R function, though, and doesn't know how to deserialize the python
floats. However, adding the R type signature *should* resolve this. With
the added signature for foo, `map` is known to return a list of
"numeric" types. So the returned values should be Serialized rather than
Passthrough.

Note, this bug has nothing to do with eta reduction, fully lambdaizing
every term raise the same issue:

```
foo xs = map (\x -> add 1.0 x) xs
```